people:
  name: 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.173.179:3306/xiaofan?useSSL=true
    username: root
    password: Guren1999$
    hikari:
      auto-commit: true
